In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [ ]:
from tensorflow.keras.models import Sequential  # Importa o modelo sequencial para criar redes neurais camada por camada
from tensorflow.keras.layers import Dense       # Importa a camada densa (totalmente conectada)
from tensorflow.keras import utils as np_utils  # Importa utilitários do Keras, como o to_categorical
from sklearn.preprocessing import LabelEncoder  # Importa o codificador para transformar rótulos em valores numéricos
from sklearn.model_selection import train_test_split  # Importa a função para dividir os dados em treino e teste


In [ ]:
base = pd.read_csv('iris_aula.csv')
base.head()

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:57: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(column, errors="raise")


sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
X = base.iloc[:, 0:4].values

In [ ]:
Y = base.iloc[:, 4].values

In [ ]:
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
Y = np_utils.to_categorical(Y)
Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
X_treinamento, X_teste, Y_treinamento, Y_teste = train_test_split(X, Y, test_size=0.25)

In [ ]:
X_treinamento.shape, X_teste.shape

((112, 4), (38, 4))

In [ ]:
Y_treinamento.shape, Y_teste.shape

((112, 3), (38, 3))

In [ ]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (4,)),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units = 4, activation = 'relu'),
    tf.keras.layers.Dense(units=3, activation = "softmax"),
])

In [ ]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
rede_neural.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['categorical_accuracy'])

In [ ]:
rede_neural.fit(X_treinamento, Y_treinamento, batch_size = 10, epochs = 1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - categorical_accuracy: 0.3577 - loss: 1.1142
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.2466 - loss: 1.1232  
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3369 - loss: 1.0926 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3623 - loss: 1.0855 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3624 - loss: 1.0675 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3186 - loss: 1.0791 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3087 - loss: 1.0782 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2987 - loss: 1.0714  
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3393 - loss: 1.0563 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3380 - loss: 1.0490 
Epoch 11

In [ ]:
rede_neural.evaluate(X_teste, Y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - categorical_accuracy: 0.9441 - loss: 0.1651


[0.15674075484275818, 0.9473684430122375]

In [ ]:
previsoes = rede_neural.predict(X_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step 
[[1.1976548e-05 9.9998802e-01 2.4086253e-08]
 [5.5482599e-04 9.3023637e-03 9.9014276e-01]
 [1.2060724e-05 9.9998790e-01 2.3799961e-08]
 [9.9999911e-01 7.9524790e-07 2.8884166e-33]
 [1.1714577e-04 9.9988276e-01 4.9009063e-10]
 [9.9999481e-01 5.1565694e-06 4.5602518e-31]
 [5.5482599e-04 9.3023637e-03 9.9014276e-01]
 [2.6066110e-03 5.0091934e-01 4.9647400e-01]
 [9.9999958e-01 3.1329446e-07 2.3186337e-34]
 [2.4667052e-06 9.9999708e-01 3.6066933e-07]
 [9.9999970e-01 2.3961132e-07 1.1218171e-34]
 [9.9996907e-01 3.0815652e-05 5.7723894e-29]
 [4.5329863e-05 9.9995464e-01 2.4805524e-09]
 [1.2621622e-05 9.9997777e-01 9.5910054e-06]
 [5.5482599e-04 9.3023637e-03 9.9014276e-01]
 [9.9999994e-01 1.4294904e-09 0.0000000e+00]
 [1.9177157e-04 9.9803680e-01 1.7714403e-03]
 [2.4823241e-03 3.2477400e-01 6.7274362e-01]
 [8.3944478e-06 9.9998719e-01 4.3878454e-06]
 [9.9999231e-01 7.5741773e-06 1.2915907e-30]
 [1.4682059e-05 9.9997240e-01 1.2816892e-05]
 [8.3633808e-05 

In [ ]:
previsoes = previsoes > 0.5
print(previsoes)

[[False  True False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]]


In [ ]:
Y_teste

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
y_test2 = [np.argmax(t) for t in Y_teste]
print(y_test2)

[np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(0), np.int64(2), np.int64(2), np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(0), np.int64(1), np.int64(1), np.int64(0), np.int64(1), np.int64(2), np.int64(1), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(1), np.int64(2), np.int64(0), np.int64(0), np.int64(2), np.int64(1), np.int64(0)]


Transformamos os dados de previsoes em suas respectivas iris, como ja foi passada.

In [ ]:
previsoes2 = [np.argmax(t) for t in previsoes]
previsoes2

[np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(2),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(0),
 np.int64(0),
 np.int64(2),
 np.int64(1),
 np.int64(0)]

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(y_test2, previsoes2)

0.9473684210526315

In [ ]:
confusion_matrix(y_test2, previsoes2)

array([[13,  0,  0],
       [ 0, 16,  1],
       [ 0,  1,  7]])